services:
  front:
    build: .
    image: ghcr.io/busheezy/sharex-paste-front:local
    volumes:
      - ./docker/dist:/vite-sharex/dist
    environment:
      VITE_APP_API_URL: "${VITE_APP_API_URL:-/api}"
      GENERATE_API: "${GENERATE_API:-true}"
